chore: update workflows from templates
nextcloud/integration_jira pull request #44
Opened 2023-06-01 15:00 UTC by nextcloud-command

This PR was automatically generated by the workflow dispatcher
Please check that there are no reverted changes before merging ⚠

See templates in https://github.com/nextcloud/.github

2023-06-01 15:28 UTC, bigcat88 commented
Do not merge this until we stop supporting NC 22/23.
Maybe we should, what do you think @julien-nc ?

2023-06-01 16:19 UTC, skjnldsv commented
Latest community supported is 25 btw :)

2023-06-01 16:19 UTC, skjnldsv requested changes
https://github.com/nextcloud/integration_jira/pull/44#issuecomment-1572271745

2023-10-24 09:14 UTC, bigcat88 approved these changes

2023-10-24 09:15 UTC, merged